name:                music-fandom-map
version:             0.1.0.0
github:              "RoryDungan/music-fandom-map"
license:             BSD3
author:              "Rory Dungan"
maintainer:          "contact@rorydungan.com"
copyright:           "2017 Rory Dungan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/music-fandom-map#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - cassava
  - bytestring
  - text
  - vector
  - bson
  - bson-mapping

executables:
  data-wrangler:
    main:                Main.hs
    source-dirs:         data-wrangler
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - music-fandom-map
    - wreq
    - lens
    - bytestring
    - mongoDB
    - vector
    - text
    - bson-mapping
  server:
    main:               Main.hs
    source-dirs:        server
    ghc-options: 
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - music-fandom-map
    - scotty
    - wai-middleware-static
    - http-types
    - mongoDB
    - bson
    - aeson
    - text
    - containers
    - bson-mapping

tests:
  music-fandom-map-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - music-fandom-map
